CREATE TABLE NINELEAPS_USER( USER_ID INT NOT NULL AUTO_INCREMENT , USERNAME VARCHAR (100) NOT NULL,
FIRSTNAME VARCHAR(200) NOT NULL,LASTNAME VARCHAR(200) NOT NULL, EMAIL VARCHAR (100)
,ROLE VARCHAR(50) NOT NULL,SSN VARCHAR(50) NOT NULL
,PRIMARY KEY (USER_ID),
CONSTRAINT USERNAME_EMAIL_SSN UNIQUE KEY(USERNAME,EMAIL,SSN));

--DROP TABLE NINELEAPS_USER;

SELECT * FROM NINELEAPS_USER;