CREATE TABLE NINELEAPS_USER( ID INT NOT NULL AUTO_INCREMENT , USERNAME VARCHAR (100) NOT NULL,
FIRSTNAME VARCHAR(200) NOT NULL,LASTNAME VARCHAR(200) NOT NULL, EMAIL VARCHAR (100),ADDRESS VARCHAR(200)
,ROLE VARCHAR(50) NOT NULL,SSN VARCHAR(50)
,PRIMARY KEY (ID));
--,CONSTRAINT USERNAME_EMAIL_SSN UNIQUE KEY(USERNAME,EMAIL,SSN));

ALTER TABLE NINELEAPS_USER RENAME COLUMN USER_ID TO ID;

DROP TABLE NINELEAPS_USER;

SELECT * FROM NINELEAPS_USER;

CREATE TABLE NINELEAPS_ORDER (ORDERID INT NOT NULL AUTO_INCREMENT , ORDERDESCRIPTION VARCHAR(500),
USER_ID INT NOT NULL, PRIMARY KEY (ORDERID));

DROP TABLE NINELEAPS_ORDER;

SELECT * FROM NINELEAPS_ORDER;